package main

// file generated by
// github.com/mh-cbon/jsoner
// do not edit

import (
	"bytes"
	"encoding/json"
	jsoner "github.com/mh-cbon/jsoner/lib"
	"io"
	"net/http"
)

// ControllerJSONGen is jsoner of *Controller.
// Controller of some resources.
type ControllerJSONGen struct {
	embed     *Controller
	finalizer jsoner.Finalizer
}

// NewControllerJSONGen constructs a jsoner of *Controller
func NewControllerJSONGen(embed *Controller, finalizer jsoner.Finalizer) *ControllerJSONGen {
	if finalizer == nil {
		finalizer = &jsoner.JSONFinalizer{}
	}
	ret := &ControllerJSONGen{
		embed:     embed,
		finalizer: finalizer,
	}
	return ret
}

//UnmarshalJSON JSON unserializes ControllerJSONGen
func (t *ControllerJSONGen) UnmarshalJSON(b []byte) error {
	var embed *Controller
	if err := json.Unmarshal(b, &embed); err != nil {
		return err
	}
	t.embed = embed
	return nil
}

//MarshalJSON JSON serializes ControllerJSONGen
func (t *ControllerJSONGen) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.embed)
}

// GetByID Decodes r as json to invoke *Controller.GetByID.
// GetByID ...
func (t *ControllerJSONGen) GetByID(r *http.Request) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error
	input := struct {
		Arg0 int
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)
	if decErr != nil {
		return nil, decErr
	}

	retVar0 := t.embed.GetByID(input.Arg0)

	output := struct {
		Arg0 Tomate
	}{
		Arg0: retVar0,
	}

	outBytes, encErr := json.Marshal(output)
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(outBytes)
		ret = &b
	}

	return ret, retErr

}

// UpdateByID Decodes reqBody as json to invoke *Controller.UpdateByID.
// Other parameters are passed straight
// UpdateByID ...
func (t *ControllerJSONGen) UpdateByID(GETid int, reqBody io.Reader) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	var decBody Tomate
	decErr := json.NewDecoder(reqBody).Decode(&decBody)
	if decErr != nil {
		return nil, decErr
	}
	retVar1 :=
		t.embed.UpdateByID(GETid, decBody)

	out, encErr := json.Marshal([]interface{}{retVar1})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr

}

// DeleteByID Decodes reqBody as json to invoke *Controller.DeleteByID.
// Other parameters are passed straight
// DeleteByID ...
func (t *ControllerJSONGen) DeleteByID(reqID int) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	retVar2 :=
		t.embed.DeleteByID(reqID)

	out, encErr := json.Marshal([]interface{}{retVar2})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr

}
